modLoader="javafml"
license="LGPLv3"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/darksonic300/AeroBlender"
displayURL="https://github.com/darksonic300/AeroBlender"

[[mods]]
    modId="aeroblender"
    version="${file.jarVersion}"
    displayName="AeroBlender"
	authors="RazorDevs"
    description="A library mod for adding biomes in a simple and compatible manner with Aether's biome/terrain system."

[[dependencies.aeroblender]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.9,)"
    ordering="NONE"
    side="BOTH"