modLoader="javafml"
license="LGPLv3"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/darksonic300/AtumBlender"
displayURL="https://github.com/darksonic300/AtumBlender"
logoFile="tb_logo.png"

[[mods]]
    modId="atumblender"
    version="${file.jarVersion}"
    displayName="AtumBlender"
	authors="RazorDevs"
    description="A library mod for adding biomes in a simple and compatible manner with Aether's biome/terrain system."

[[dependencies.atumblender]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.9,)"
    ordering="NONE"
    side="BOTH"