modLoader = "javafml"
loaderVersion = "[1,)"
license="LGPL-3.0"
issueTrackerURL = "https://github.com/RazorDevs/AeroBlender/issues"

[[mods]]
modId="aeroblender"
version="${file.jarVersion}"
displayName="AeroBlender"
logoFile="aeroblender.png"
credits="Credits goes to Glitchfiend Mods."
authors="RazorDevs"
description='''
AeroBlender is a library mod for adding biomes in a simple and compatible manner with Aether's biome/terrain system, using Terrablender.
'''

[[dependencies.aeroblender]]
modId="neoforge"
type = "required"
versionRange="[20.4.167,)"
ordering="NONE"
side="BOTH"

[[dependencies.aeroblender]]
modId="minecraft"
type = "required"
versionRange="[1.20.4]"
ordering="NONE"
side="BOTH"

[[dependencies.aeroblender]]
modId="terrablender"
type="required"
versionRange="[3.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.aeroblender]]
modId="aether"
type="required"
versionRange="[1.20.4-1.4.0-neoforge,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="aeroblender.mixins.json"