modLoader = "javafml"
loaderVersion = "[1,)"
license="LGPL-3.0"
issueTrackerURL = "https://github.com/RazorDevs/AeroBlender/issues"

[[mods]]
modId="aeroblender"
version="${file.jarVersion}"
displayName="AeroBlender"
logoFile="aeroblender.png"
credits="Credits goes to the terrablender team"
authors="RazorDevs"
description='''
AeroBlender is a library mod for adding biomes in a simple and compatible manner with Aether's biome/terrain system, using Terrablender.
'''

[[dependencies.aeroblender]]
modId="neoforge"
mandatory=true
versionRange="[1,)"
ordering="NONE"
side="BOTH"
[[dependencies.aeroblender]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.aeroblender]]
modId="terrablender"
mandatory=true
versionRange="[3.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.aeroblender]]
modId="aether"
mandatory=true
versionRange="[1.20.2-1.3.0-neoforge,)"
ordering="AFTER"
side="BOTH"